// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Intervals.djinni

package rharriso.tonetimer;

public final class Config {


    /*package*/ final int intervalDuration;

    /*package*/ final int intervalBreak;

    /*package*/ final int setSize;

    /*package*/ final int setBreak;

    /*package*/ final int setCount;

    public Config(
            int intervalDuration,
            int intervalBreak,
            int setSize,
            int setBreak,
            int setCount) {
        this.intervalDuration = intervalDuration;
        this.intervalBreak = intervalBreak;
        this.setSize = setSize;
        this.setBreak = setBreak;
        this.setCount = setCount;
    }

    public int getIntervalDuration() {
        return intervalDuration;
    }

    public int getIntervalBreak() {
        return intervalBreak;
    }

    public int getSetSize() {
        return setSize;
    }

    public int getSetBreak() {
        return setBreak;
    }

    public int getSetCount() {
        return setCount;
    }

    @Override
    public String toString() {
        return "Config{" +
                "intervalDuration=" + intervalDuration +
                "," + "intervalBreak=" + intervalBreak +
                "," + "setSize=" + setSize +
                "," + "setBreak=" + setBreak +
                "," + "setCount=" + setCount +
        "}";
    }

}
