// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Intervals.djinni

package rharriso.tonetimer;

public abstract class SettingsView {
    public abstract void setIntervalDuration(int d);

    public abstract void setIntervalBreak(int b);

    public abstract void setSetSize(int s);

    public abstract void setSetBreak(int b);

    public abstract void setSetCount(int c);
}
