// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#include "NativeTimerView.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeTimerView::NativeTimerView() : ::djinni::JniInterface<::tonetimer::TimerView, NativeTimerView>() {}

NativeTimerView::~NativeTimerView() = default;

NativeTimerView::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeTimerView::JavaProxy::~JavaProxy() = default;

void NativeTimerView::JavaProxy::setStateTime(int32_t c_t) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeTimerView>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setStateTime,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_t)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeTimerView::JavaProxy::setTotalTime(int32_t c_t) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeTimerView>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setTotalTime,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_t)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeTimerView::JavaProxy::setRemainTime(int32_t c_t) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeTimerView>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setRemainTime,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_t)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
