// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#include "NativeSettingsView.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeSettingsView::NativeSettingsView() : ::djinni::JniInterface<::tonetimer::SettingsView, NativeSettingsView>() {}

NativeSettingsView::~NativeSettingsView() = default;

NativeSettingsView::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeSettingsView::JavaProxy::~JavaProxy() = default;

void NativeSettingsView::JavaProxy::setIntervalDuration(int32_t c_d) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeSettingsView>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setIntervalDuration,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_d)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeSettingsView::JavaProxy::setIntervalBreak(int32_t c_b) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeSettingsView>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setIntervalBreak,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_b)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeSettingsView::JavaProxy::setSetSize(int32_t c_s) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeSettingsView>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setSetSize,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_s)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeSettingsView::JavaProxy::setSetBreak(int32_t c_b) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeSettingsView>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setSetBreak,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_b)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeSettingsView::JavaProxy::setSetCount(int32_t c_c) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeSettingsView>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setSetCount,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_c)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
