// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#pragma once

#include "djinni_support.hpp"
#include "timerView.hpp"

namespace djinni_generated {

class NativeTimerView final : ::djinni::JniInterface<::tonetimer::TimerView, NativeTimerView> {
public:
    using CppType = std::shared_ptr<::tonetimer::TimerView>;
    using CppOptType = std::shared_ptr<::tonetimer::TimerView>;
    using JniType = jobject;

    using Boxed = NativeTimerView;

    ~NativeTimerView();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeTimerView>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeTimerView>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeTimerView();
    friend ::djinni::JniClass<NativeTimerView>;
    friend ::djinni::JniInterface<::tonetimer::TimerView, NativeTimerView>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::tonetimer::TimerView
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void displayText(const std::string & s) override;

    private:
        friend ::djinni::JniInterface<::tonetimer::TimerView, ::djinni_generated::NativeTimerView>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("rharriso/tonetimer/TimerView") };
    const jmethodID method_displayText { ::djinni::jniGetMethodID(clazz.get(), "displayText", "(Ljava/lang/String;)V") };
};

}  // namespace djinni_generated
