// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#pragma once

#include "djinni_support.hpp"
#include "timerViewModel.hpp"

namespace djinni_generated {

class NativeTimerViewModel final : ::djinni::JniInterface<::tonetimer::TimerViewModel, NativeTimerViewModel> {
public:
    using CppType = std::shared_ptr<::tonetimer::TimerViewModel>;
    using CppOptType = std::shared_ptr<::tonetimer::TimerViewModel>;
    using JniType = jobject;

    using Boxed = NativeTimerViewModel;

    ~NativeTimerViewModel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeTimerViewModel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeTimerViewModel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeTimerViewModel();
    friend ::djinni::JniClass<NativeTimerViewModel>;
    friend ::djinni::JniInterface<::tonetimer::TimerViewModel, NativeTimerViewModel>;

};

}  // namespace djinni_generated
