// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#include "NativeConfig.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeConfig::NativeConfig() = default;

NativeConfig::~NativeConfig() = default;

auto NativeConfig::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeConfig>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.intervalDuration)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.intervalBreak)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.setSize)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.setBreak)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.setCount)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeConfig::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeConfig>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mIntervalDuration)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mIntervalBreak)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mSetSize)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mSetBreak)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mSetCount))};
}

}  // namespace djinni_generated
