// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

package rharriso.tonetimer;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class HelloViewModel {
    public abstract String getGreeting(String name);

    private static final class CppProxy extends HelloViewModel
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public String getGreeting(String name)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getGreeting(this.nativeRef, name);
        }
        private native String native_getGreeting(long _nativeRef, String name);
    }
}
