// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

package rharriso.tonetimer;

public abstract class TimerView {
    public abstract void setStateTime(int t);

    public abstract void setTotalTime(int t);

    public abstract void setRemainTime(int t);
}
