// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#import "TTConfig+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Config::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.intervalDuration),
            ::djinni::I32::toCpp(obj.intervalBreak),
            ::djinni::I32::toCpp(obj.setSize),
            ::djinni::I32::toCpp(obj.setBreak),
            ::djinni::I32::toCpp(obj.setCount)};
}

auto Config::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TTConfig alloc] initWithIntervalDuration:(::djinni::I32::fromCpp(cpp.intervalDuration))
                                        intervalBreak:(::djinni::I32::fromCpp(cpp.intervalBreak))
                                              setSize:(::djinni::I32::fromCpp(cpp.setSize))
                                             setBreak:(::djinni::I32::fromCpp(cpp.setBreak))
                                             setCount:(::djinni::I32::fromCpp(cpp.setCount))];
}

}  // namespace djinni_generated
