// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#import <Foundation/Foundation.h>

@interface TTConfig : NSObject
- (nonnull instancetype)initWithIntervalDuration:(int32_t)intervalDuration
                                   intervalBreak:(int32_t)intervalBreak
                                         setSize:(int32_t)setSize
                                        setBreak:(int32_t)setBreak
                                        setCount:(int32_t)setCount;
+ (nonnull instancetype)configWithIntervalDuration:(int32_t)intervalDuration
                                     intervalBreak:(int32_t)intervalBreak
                                           setSize:(int32_t)setSize
                                          setBreak:(int32_t)setBreak
                                          setCount:(int32_t)setCount;

@property (nonatomic, readonly) int32_t intervalDuration;

@property (nonatomic, readonly) int32_t intervalBreak;

@property (nonatomic, readonly) int32_t setSize;

@property (nonatomic, readonly) int32_t setBreak;

@property (nonatomic, readonly) int32_t setCount;

@end
