// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#import <Foundation/Foundation.h>
@class TTHelloWorld;


@interface TTHelloWorld : NSObject

+ (nullable TTHelloWorld *)create;

- (nonnull NSString *)getGreeting:(nonnull NSString *)name;

@end
