// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#import <Foundation/Foundation.h>


@interface TTHelloViewModel : NSObject

- (nonnull NSString *)getGreeting:(nonnull NSString *)name;

@end
