// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#import "TTHelloWorld+Private.h"
#import "TTHelloWorld.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "TTHelloWorld+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface TTHelloWorld ()

- (id)initWithCpp:(const std::shared_ptr<::tonetimer::HelloWorld>&)cppRef;

@end

@implementation TTHelloWorld {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::tonetimer::HelloWorld>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::tonetimer::HelloWorld>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable TTHelloWorld *)create {
    try {
        auto r = ::tonetimer::HelloWorld::create();
        return ::djinni_generated::HelloWorld::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getGreeting:(nonnull NSString *)name {
    try {
        auto r = _cppRefHandle.get()->getGreeting(::djinni::String::toCpp(name));
        return ::djinni::String::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto HelloWorld::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto HelloWorld::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<TTHelloWorld>(cpp);
}

}  // namespace djinni_generated

@end
