// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#import <Foundation/Foundation.h>
@class TTSettingsViewModel;


/**
 *
 * Settings View
 *
 */
@interface TTSettingsViewModel : NSObject

+ (nullable TTSettingsViewModel *)create;

- (void)incIntervalDuration;

- (void)decIntervalDuration;

- (void)incIntervalBreak;

- (void)decIntervalBreak;

- (void)incSetSize;

- (void)decSetSize;

- (void)incSetCount;

- (void)decSetCount;

- (void)incSetBreak;

- (void)decSetBreak;

@end
