// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#import "TTSettingsViewModel+Private.h"
#import "TTSettingsViewModel.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface TTSettingsViewModel ()

- (id)initWithCpp:(const std::shared_ptr<::tonetimer::SettingsViewModel>&)cppRef;

@end

@implementation TTSettingsViewModel {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::tonetimer::SettingsViewModel>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::tonetimer::SettingsViewModel>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)setIntervalDuration:(int32_t)d {
    try {
        _cppRefHandle.get()->setIntervalDuration(::djinni::I32::toCpp(d));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setIntervalBreak:(int32_t)b {
    try {
        _cppRefHandle.get()->setIntervalBreak(::djinni::I32::toCpp(b));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setSetSize:(int32_t)s {
    try {
        _cppRefHandle.get()->setSetSize(::djinni::I32::toCpp(s));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setSetBreak:(int32_t)b {
    try {
        _cppRefHandle.get()->setSetBreak(::djinni::I32::toCpp(b));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setSetCount:(int32_t)c {
    try {
        _cppRefHandle.get()->setSetCount(::djinni::I32::toCpp(c));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto SettingsViewModel::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto SettingsViewModel::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<TTSettingsViewModel>(cpp);
}

}  // namespace djinni_generated

@end
