// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#include "settingsViewModel.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TTSettingsViewModel;

namespace djinni_generated {

class SettingsViewModel
{
public:
    using CppType = std::shared_ptr<::tonetimer::SettingsViewModel>;
    using CppOptType = std::shared_ptr<::tonetimer::SettingsViewModel>;
    using ObjcType = TTSettingsViewModel*;

    using Boxed = SettingsViewModel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

