// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#import <Foundation/Foundation.h>


@protocol TTSettingsView

- (void)setIntervalDuration:(int32_t)d;

- (void)setIntervalBreak:(int32_t)b;

- (void)setSetSize:(int32_t)s;

- (void)setSetBreak:(int32_t)b;

- (void)setSetCount:(int32_t)c;

@end
