// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#include "settingsView.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol TTSettingsView;

namespace djinni_generated {

class SettingsView
{
public:
    using CppType = std::shared_ptr<::tonetimer::SettingsView>;
    using CppOptType = std::shared_ptr<::tonetimer::SettingsView>;
    using ObjcType = id<TTSettingsView>;

    using Boxed = SettingsView;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

