// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#import "TTTimerView+Private.h"
#import "TTTimerView.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class TimerView::ObjcProxy final
: public ::tonetimer::TimerView
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void setStateTime(int32_t c_t) override
    {
        @autoreleasepool {
            [Handle::get() setStateTime:(::djinni::I32::fromCpp(c_t))];
        }
    }
    void setTotalTime(int32_t c_t) override
    {
        @autoreleasepool {
            [Handle::get() setTotalTime:(::djinni::I32::fromCpp(c_t))];
        }
    }
    void setRemainTime(int32_t c_t) override
    {
        @autoreleasepool {
            [Handle::get() setRemainTime:(::djinni::I32::fromCpp(c_t))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto TimerView::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto TimerView::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
