// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#import <Foundation/Foundation.h>


@protocol TTTimerView

- (void)displayText:(nonnull NSString *)s;

@end
