// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#import <Foundation/Foundation.h>
@class TTTimerViewModel;
@protocol TTTimerView;


/**
 *
 * Timer View 
 *
 */
@interface TTTimerViewModel : NSObject

+ (nullable TTTimerViewModel *)createWithView:(nullable id<TTTimerView>)view;

- (void)pause;

- (void)play;

- (void)reset;

@end
