// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#import <Foundation/Foundation.h>


@protocol TTTimerView

- (void)setStateTime:(int32_t)t;

- (void)setTotalTime:(int32_t)t;

- (void)setRemainTime:(int32_t)t;

@end
