// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#import "TTTimerViewModel+Private.h"
#import "TTTimerViewModel.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "TTTimerView+Private.h"
#import "TTTimerViewModel+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface TTTimerViewModel ()

- (id)initWithCpp:(const std::shared_ptr<::tonetimer::TimerViewModel>&)cppRef;

@end

@implementation TTTimerViewModel {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::tonetimer::TimerViewModel>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::tonetimer::TimerViewModel>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable TTTimerViewModel *)createWithView:(nullable id<TTTimerView>)view {
    try {
        auto r = ::tonetimer::TimerViewModel::createWithView(::djinni_generated::TimerView::toCpp(view));
        return ::djinni_generated::TimerViewModel::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)pause {
    try {
        _cppRefHandle.get()->pause();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)play {
    try {
        _cppRefHandle.get()->play();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)reset {
    try {
        _cppRefHandle.get()->reset();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)onTick {
    try {
        _cppRefHandle.get()->onTick();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto TimerViewModel::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto TimerViewModel::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<TTTimerViewModel>(cpp);
}

}  // namespace djinni_generated

@end
