// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#include "timerView.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol TTTimerView;

namespace djinni_generated {

class TimerView
{
public:
    using CppType = std::shared_ptr<::tonetimer::TimerView>;
    using CppOptType = std::shared_ptr<::tonetimer::TimerView>;
    using ObjcType = id<TTTimerView>;

    using Boxed = TimerView;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

