// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#include "timerViewModel.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TTTimerViewModel;

namespace djinni_generated {

class TimerViewModel
{
public:
    using CppType = std::shared_ptr<::tonetimer::TimerViewModel>;
    using CppOptType = std::shared_ptr<::tonetimer::TimerViewModel>;
    using ObjcType = TTTimerViewModel*;

    using Boxed = TimerViewModel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

