// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#pragma once

#include <memory>
#include <string>

namespace tonetimer {

class HelloWorld {
public:
    virtual ~HelloWorld() {}

    static std::shared_ptr<HelloWorld> create();

    virtual std::string getGreeting(const std::string & name) = 0;
};

}  // namespace tonetimer
