// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#pragma once

#include <string>

namespace tonetimer {

class HelloViewModel {
public:
    virtual ~HelloViewModel() {}

    virtual std::string getGreeting(const std::string & name) = 0;
};

}  // namespace tonetimer
