// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#pragma once

#include <cstdint>

namespace tonetimer {

class SettingsViewModel {
public:
    virtual ~SettingsViewModel() {}

    virtual void setIntervalDuration(int32_t d) = 0;

    virtual void setIntervalBreak(int32_t b) = 0;

    virtual void setSetSize(int32_t s) = 0;

    virtual void setSetBreak(int32_t b) = 0;

    virtual void setSetCount(int32_t c) = 0;
};

}  // namespace tonetimer
