// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ToneTimer.djinni

#pragma once

#include <string>

namespace tonetimer {

class TimerView {
public:
    virtual ~TimerView() {}

    virtual void displayText(const std::string & s) = 0;
};

}  // namespace tonetimer
