// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Intervals.djinni

#pragma once

#include <cstdint>
#include <utility>

struct Config final {
    int32_t intervalDuration;
    int32_t intervalBreak;
    int32_t setSize;
    int32_t setBreak;
    int32_t setCount;

    Config(int32_t intervalDuration_,
           int32_t intervalBreak_,
           int32_t setSize_,
           int32_t setBreak_,
           int32_t setCount_)
    : intervalDuration(std::move(intervalDuration_))
    , intervalBreak(std::move(intervalBreak_))
    , setSize(std::move(setSize_))
    , setBreak(std::move(setBreak_))
    , setCount(std::move(setCount_))
    {}
};
