// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Intervals.djinni

#pragma once

#include <cstdint>
#include <utility>

struct Config final {
    int32_t intervalDuration = 30;
    int32_t intervalBreak = 45;
    int32_t setSize = 5;
    int32_t setBreak = 90;
    int32_t setCount = 5;

    Config(int32_t intervalDuration_,
           int32_t intervalBreak_,
           int32_t setSize_,
           int32_t setBreak_,
           int32_t setCount_)
    : intervalDuration(std::move(intervalDuration_))
    , intervalBreak(std::move(intervalBreak_))
    , setSize(std::move(setSize_))
    , setBreak(std::move(setBreak_))
    , setCount(std::move(setCount_))
    {}
};
